remote_theme: "mmistakes/minimal-mistakes@4.14.2"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
title: ".::zludosan::."

author:
  name: "zludosan"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an amazing person."
  location: "Somewhere"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"
