remote_theme: "mmistakes/minimal-mistakes@4.16.4"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
title: ".::zludosan::."

author:
  name: "zludosan"
  avatar: "https://cdn4.iconfinder.com/data/icons/free-ui/64/v-33-128.png"
  bio: "Description"
  location: "Somewhere"
  links:
    - label: "Random link"
      icon: "fas fa-fw fa-link"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: ""

